
/*
	► INSERT: SidtefimModulo */
	INSERT INTO SidtefimModulo
	VALUES
	(
		'SITRAN', 1, 'Sistema de Trazabilidad de Nacionalización', 'Sistema de Trazabilidad de Nacionalización', '1.0'
	)

SELECT * FROM dbo.SidInterpol
GO

/*
	► INSERT: SidtefimProcedimiento
	► SELECT * FROM SidtefimProcedimiento */
INSERT INTO SidtefimProcedimiento(bActivo, sIcono, sNombre, sRuta, sIdModulo) VALUES(1,'AddBox','PARA EVALUACIÓN','/test','SITRAN')
INSERT INTO SidtefimProcedimiento(bActivo, sIcono, sNombre, sRuta, sIdModulo) VALUES(1,'Check','EN PROYECTO EVALUACIÓN','/test','SITRAN')
INSERT INTO SidtefimProcedimiento(bActivo, sIcono, sNombre, sRuta, sIdModulo) VALUES(1,'Clear','NO LEIDOS','/test','SITRAN')
INSERT INTO SidtefimProcedimiento(bActivo, sIcono, sNombre, sRuta, sIdModulo) VALUES(1,'DeleteOutline','REGISTRAR PROCEDIMIENTO','/test','SITRAN')
INSERT INTO SidtefimProcedimiento(bActivo, sIcono, sNombre, sRuta, sIdModulo) VALUES(1,'ChevronRight','PARA ASIGNAR','/test','SITRAN')
INSERT INTO SidtefimProcedimiento(bActivo, sIcono, sNombre, sRuta, sIdModulo) VALUES(1,'Edit','CONSULTAS','/test','SITRAN')

INSERT INTO SidEmpresa(sDescripcion, bActivo) VALUES('Terminales Terrestres', 1)
INSERT INTO SidEmpresa(sDescripcion, bActivo) VALUES('Lugares Públicos', 1)
INSERT INTO SidEmpresa(sDescripcion, bActivo) VALUES('Establecimientos de Hospedajes', 1)
INSERT INTO SidEmpresa(sDescripcion, bActivo) VALUES('Aeropuerto Internacional Jorge Chavez ', 1)

/*
	► INSERT: SidActividad */
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Elaboración de informes técnicos de expedientes en tramite y fiscalización posterior')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Revisión y seguimiento de expedientes y documentos para atención')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Toma de entrevistas virtuales')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Gestión documental')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Toma de entrevista virtual')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Inventario de hallazgos')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Elaboración de informes técnicos de expedientes PTP')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Consolidación de información y actualización de cuadros de Fiscalización Posterior y otros')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Gestión documental y coordinación')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Consolidación de información y actualización de cuadros de Fiscalización Posterior y otros.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Gestión documental y coodinación.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Elaboración de documentos administrativos.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Revisión de documentos de la SFM.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Coordinaciones administrativas')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Revisión de informes en base a diversos medios periodísticos que involucran a ciudadanos extranjeros en actos ilícitos.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Otras actividades.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Revisión y control de calidad de informes técnicos de expedientes de Fiscalización Posterior y en trámite')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Revisión y aportes a documentos normativos y del SGC')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Coordinaciones administrativas múltiples, y revisión de documentos de la SFM')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Gestionar y monitorear los requerimientos operativos y administrativos necesarios para el funcionamiento de la Subdirección Fiscalización Migratoria.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Gestionar y coordinar las unidade móviles de la SFM, los servicios y apoyo a las otras unidades orgánicas de la DGTFM.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Realizar el seguimiento mensual al POI 2021, a fin de cumplir las metas fisicas establecidas para la SFM')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Consolidar información de producción y asistencia del personal de la SFM')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Gestión Documental (Comunicación de Documentos y atención a través del correo de la SGVF)')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Asignación de Documentos a través del SGD')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Digitalización y de expedientes')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Revisión de informes sobre revisión realizada a diversos medios periodísticos que involucran a ciudadanos extranjeros en actos ilícitos.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Elaboración de informes y hojas de elevación.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Visitas IN SITU en domicilios de administrados')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Diligenciamiento y seguimiento de documentos')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Consultas en aplicativos SIM INM, SIM RCM y SIM DNV')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Operativos de Fiscalización Migratoria')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Actividades de fiscalización posterior.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Seguimiento de documentos de fiscalización posterior.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Consolidado de información.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Elaboración de informes administrativos.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Consolidación de información.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Elaboración de documentos adminsitrativos.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Elaboración de documentos.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Consultas en aplicativos SIM INM, SIM RCM y SIM DNV.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Participacion de Operativos de Fiscalizacion Posterior.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Diligenciamiento y seguimiento de documentos.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Participación de operativos de Fiscalización Posterior.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Visitas IN SITU en domicilios de administrados.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Atención de diversos proveídos ( consultas, proyectos de normativas, procedimientos, etc.)')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Revisión de documentos normativos para emitir opinión')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Verificación de documentación en el SGD.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Verificar y asignar la documentación virtual a través del SGD')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Gestión Documental (Comunicación de Documentos correo)')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Archivar y ordenar el archivo físico de la documentación que se ha generado en el presente año en los archivadores de la SGVF')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACTIVIDAD', 'Realizar el archivamiento según procedimiento de la documentación de la SGVF para enviar al archivo central (Ordenamiento del Archivo - Año 2017)')

INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Informes técnicos de expedientes de fiscalización posterior.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Cartas eleaboradas.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Oficio emitido.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Proveidos recepcionados y anexados a expedientes digitales.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Coordinaciones para emisión de informes.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Carta.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Foleación/union de expediente digital de nacionalizacion por matrimonio.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Correcciones de Informes de tramite de nacionbalizacion por matrimonio.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Proyecto de informe de nacionalizacion por matrimonio.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Toma de entrevistas virtuales.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Recepcion de proveidos y sus respectivas descargas.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Revisión de expediente de tramite por nacionalización por matrimonio.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Informe de nacionalización por matrimonio.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Entrevistas virtuales.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Busqueda en sistemas de migraciones y/o afines.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Elaboracion de actas fotograficas.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Digitalizaciones de expediente u otros documentos y foliados respectivamente.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Verificación domiciliaria insitu.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Hoja de Elevación elaborada.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Expedientes revisados para le emisión de informes.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Expedientes Unificados y foleados en formato pdf.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Proyecto de informe de fiscalización posterior revisado.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Proyecto de cartas y oficios revisados.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Expedientes revisados para emisión de informes.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Proyecto de informe técnico de fiscalización posterior.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Coordinaciones vía telefónica para la emisión de informes.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Capacitación.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Proyectos de Informes técnicos de expedientes de fiscalización posterior elaborados.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Expedientes organizados con diligencias emitidas.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Proyectos de informes de fiscalización posterior revisados.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Proyectos de Cartas y oficios revisados.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Expedientes revisados de fiscalización posterior para emisión de diligencias.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Correos emitidos para seguimiento de diligencias.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Consolidados de reporte de produccion semanal.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Memorandos.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Proyecto de memorando.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Proyecto de hoja de elevacion.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Actualizaciones y/o revision de la base de tramite de nacionalizacion por matrimonio.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Busquedas en Sunat y/o aplicativos de migraciones.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Recepción de proveidos y respectivas descargas del contenido delas mismas.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Verificacion de hallazgos de fiscalizacion posterior.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Reunion de la SFM(coordinadores).')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Coordinaciones con equipo de trabajo respecto a la base de hospedajes, aclaraciones de consultas entre otros y /o de tramite de nacionalizacion por matrimonio.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Actualizaciones de la base de datos de fiscalización posterior 2021.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Proveídos recepcionado y atendidos.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Actualizaciones de diligencias de fiscalización posterior.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Consolidado semanal de Reporte Semanal de Actividades.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Llamadas de coordinación.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Correos remitidos para coordinación de actividades de fiscalización posterior y respuesta de solicitud de información.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Expedientes diligitales revisados que contengan diligencias.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Elaboración de cuadro resumen de avance carga por abogado.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Proveido emitido para asignación de expedientes.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Capacitaciones.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Revisiones de Directiva para emitir comentario.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Informes de fiscalización posterior revisados para verificar hallazgos.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Búsqueda de información de años 2019 y 2020 para informe de gestión.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Informes sobre la gestión de la SFM.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Hojas de Elevación sobre la gestión de la SFM.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Órdenes de operativos de verificación y fiscalización migratoria.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Revisiones de informes sobre ciudadanos extranjeros en actos ilícitos reportados en medios periodísticos.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Revisión de documentos administrativos relacionados a antecedentes internacionales de ciudadanos extranjeros.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Opiniones sobre documentos normativos (Procedimiento e Instructivo sobre Emisión de Carné de Extranjería por cambio de calidad migratoria).')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Requerimiento de pedido sobre una reunión que solictó una empresa de tecnología de control de fronteras.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Revisión de la propuesta de cadena de valor de los Procesos Misionales.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Coordinaciones para la programación de entrevistas para administrados.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Coordinación para elaboración de cronograma de operativos en el AIJCH en el mes de mayo.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Coordinaciones, supervisiones y control de los operativos de verificación y fiscalización migratoria.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Coordinaciones con la Subdirectora de Fiscalización Migratoria.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Coordinación para la elaboración de actas de desplazamiento de bienes patrimoniales para el desarrollo de operativos.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Coordinaciones con fiscalizadores en atención a las actividades de verificación y fiscalización.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Hojas de Elevación.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Proveídos.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Revisiones y control de calidad de informes tecnicos y documentos colgados por el personal en el SGD.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Coordinaciones telefónicas para el levantamiento de observaciones.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Correos electrónicos emitidos a servidores de la SFM.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Hallazgos caso universidad Unión.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Correos enviados.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Hojas de Elevación elaboradas.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Recepción de Proveídos.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Informe.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Reporte te de Personal por temas de vacuna COVID-19.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Programación de actividades para la primera semana de mayo.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Coordinaciones con los encargados para el levantamiento del inventario anual de bienes patrimoniales.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Coordinación con OTIC para los accesos y bajas de personal nuevo y saliente.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Consolidado de producción semanal del personal.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Coordinaciones con RH por errores en certificados de personal, coordinaciones con Dirección por el tema de capacitación del RIM, además de coordinar los apoyos de movilidades a otras unidades orgánica y las comisiones de servicio diarias para el traslado del personal a diferentes distritos de Lima Metropolitana.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Descargas y Renombramiento de documentación.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Envío de documentación a entidades públicas y/o administrados.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Documentos archivados digitalmente.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Respuesta a solicitud(es) de información interna y externa.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Coordinaciones para actividades a realizar (diligenciamiento de documentos).')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Proveidos elaborados de asignación documental.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Atención de llamadas telefónicas.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Digitalizaciones de documentos.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Revisión en diferentes medios periodísticos, noticias que impliquen a extranjeros en delitos.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Informes sobre ciudadanos extranjeros en actos ilícitos reportados en medios periodísticos.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Hoja de elevación.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Incidencia en la opción de busqueda de registro en el Aplicativo SIM-NAC reportado a mesa de servicio atraves del Correo Electrónico Institucional.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Solicitud de Actas de Desplazamiento de Bienes para desarrollo de Activdad Operativa (Operativos de Verificación y Fiscalización en el AIJCH).')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Apoyo en la elaboración del Cronograma y formación de grupos de los Operativos de Verificación y Fiscalización Migratoria correspondiente al mes de Mayo 2021 en el Aeropuerto Internacional Jorge Chávez.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Cartas elaboradas.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Oficio elaborado.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Proveídos recepcionados y anexados a expedientes digitales.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Expedientes de pasaporte electronico revisado para elaboración de informes.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Proyectos de informe de pasaporte electrónico.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Administrados consultados en plataforma INTERPOL.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Notificaciones de documentos IN-SITU.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Expedientes revisados para emisión de reiterativos de información.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Operativo presencial en Aeropuerto Jorge Chávez.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Documentos con sustento fotográfico elaborados.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Seguimiento de respuesta de 15 solicitudes de información.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Actualización de base de expedientes de nacionalización.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Actualización de cuadro de prorroga de residencia y Nacionalización.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Seguimiento de respuestas trámites de prórroga de residencia y nacionalización.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Validaciones de fichas de interpol.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Diligencias de la SFM.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Apoyo en la actualización de cuadros sobre programación de entrevistas virtuales de la SFM.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Apoyo en la elaboración del informe sobre los compromisos de las partes del convenio interinstitucional entre el Ministerio de Transporte y Migraciones.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Apoyo en operativo de verificación y fiscalización migratoria en el Aeropuerto Internacional Jorge Chávez.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Apoyo en la elaboración del informe sobre la remisión del protocolo e instructivo de verificación y fiscalización migratoria en los Puestos de Verificación Migratoria a la DGTFM para su aprobación.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Apoyo en la elaboración de la Orden de operativo de verificación y fiscalización migratoria en el Aeropuerto Internacional Jorge Chávez del 30/04/2021.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Apoyo en la elaboración del Informe sobre el Convenio entre el Poder Judicial y MIGRACIONES.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Reporte integral semanal.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Actualización de cuadro integral de operativos y documentos anexos.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Actualización de cuadro de intervenidos en operativos 2021.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Actualizaciones de carpetas de operativos.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Proyecto de informe de pasaporte electronico- fiscalización posterior.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Oficios de fiscalizacion posterior.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Recepcion de proveidos y sus descarga respectivas.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Revisiones de expedientes de fiscalizacion posterior.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Actualizacion de base de excel de fiscalizacion posterior - naciobalización por matrimonio y/o prorroga de residencia.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Verificacionesen página de SUNAT y/o otros aplicativos afines respecto al estado de las deligencias de los expedientes de prórroga de residencia y/o nacionaizacion por matrimonio.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Participacion en operativo de fiscalizacion en el aeropuerto.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Cartas de establecimientos de hospedajes.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Actualizaciones de registros en la base de establecimiento de hospedajes 2021.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Proyectos de cartas de establecimientos de hospedajes.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Búsquedas y/o validaciones en sistemas SIM-IN, SIM RCM, DNV y/o aplicativos complementarios.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Validaciones de cargos de notificación de tablecimientos de hospedajes.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Proyectos de informes de fiscalización.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Actualización de base de expedientes.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Ciudadanos intervenidos.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Actualización de diligencias.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Administrados consultados en SIM INM para completar datos de excel de Fiscalización Posterior 2021.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Reunión de Trabajo Validación Visa Humanitaria.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Revisiones de base legal para la emisión de opiones solicitadas.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Seguimiento a Oficio 738.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Descargas de expedientes digitales.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Seguimiento de expedientes vía telefónica y vía correo electrónico.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Proveidos emitidos.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Proveidos recibidos.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Seguimientos a los documentos en espera de respuesta por parte de las entidades publicas como RENAJU, INTERPOL,INPE ENTRE OTROS.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Envíos de correos electrónicos para solicitar respuesta del documento enviado.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Llamadas telefónicas las diversas entidades públicas para consulta de respuestas de documentación enviada por Migraciones.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Coordinaciones por correo y llamadas telefonicas con los servidores de trabajo.')
INSERT INTO SidActividad(sTipo, sDescripcion) VALUES('ACCION', 'Licencia con goce.')
